from __future__ import annotations

import subprocess
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[3]


def _run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, cwd=str(_REPO_ROOT), check=check)


def create_pr(
    signal_name: str,
    dataset_id: str,
    eval_result: dict,
    files: dict[str, str],
    dry_run: bool = False,
) -> str | None:
    branch = f"agent/add-{signal_name}-collector"

    if dry_run:
        print(f"[dry-run] Would create branch {branch} and open PR for {signal_name} (dataset {dataset_id})")
        return None

    _run(["git", "checkout", "-b", branch])

    for rel_path, content in files.items():
        dest = _REPO_ROOT / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content)

    changed = [
        f"src/nyc_pulse/collectors/{signal_name}.py",
        f"src/nyc_pulse/signals/{signal_name}.py",
        f"tests/test_agent_{signal_name}.py",
        "src/nyc_pulse/cli.py",
        "api/routes/events.py",
        "api/routes/block.py",
        "agent/state.json",
    ]
    _run(["git", "add"] + changed)
    _run(["git", "commit", "-m", f"feat(agent): add {signal_name} collector from dataset {dataset_id}"])
    _run(["git", "push", "origin", branch])

    body = (
        f"**Dataset:** [{dataset_id}](https://data.cityofnewyork.us/d/{dataset_id})\n"
        f"**Score:** {eval_result['score']}/10\n"
        f"**Rationale:** {eval_result['rationale']}\n\n"
        f"> Scorer uses flat event count. Tune weights in `signals/{signal_name}.py` after review.\n\n"
        "Auto-generated by `nyc-pulse agent discover`"
    )

    pr_result = _run([
        "gh", "pr", "create",
        "--title", f"feat(agent): {signal_name} collector (dataset {dataset_id})",
        "--body", body,
        "--label", "agent-generated",
        "--head", branch,
    ])

    pr_url = pr_result.stdout.strip()

    _run(["gh", "pr", "merge", "--auto", "--squash", pr_url], check=False)
    _run(["git", "checkout", "master"])

    return pr_url
